server:
  port: 8761
eureka:
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://user:8888@localhost:8761/eureka
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
security:
  basic: 
    enabled: true
  user:
    name: user
    password: 8888
spring:
  application:
    name: server-center
