spring:
  application:
    name: feign-consumer1
server:
  port: 8680
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:8888@localhost:8761/eureka,http://user:8888@localhost:8762/eureka,http://user:8888@localhost:8763/eureka
  healthcheck:
    enable: true
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${server.port}
