server:
  port: 8581
  tomcat:
    accesslog:
      enabled: true
  error:
    whitelabel:
      enabled: false
spring: 
  application: 
    name: user-supplier
eureka: 
  client: 
    serviceUrl:
      defaultZone: http://user:8888@localhost:8761/eureka,http://user:8888@localhost:8762/eureka,http://user:8888@localhost:8763/eureka
    healthcheck:
      enable: true
  instance:
    hostname: user-1
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${server.port}
